### ISSUE TITLE
Criar primeiros gráficos para fila de Acc. thread com auxílio do Crives

### ISSUE THREAD

**Issue by luhnery** [luhnery/Blackops#15]

**Comment by Cesar-Augusto-cw** [comment]
Durante conversa com Pantoja em 07/02 visualizamos algumas formas de fazer os dashboards.   2 widgets criados (dash e tabela), precisamos criar mais.

Enquanto isso, estou atualizando os dados numa [planilha](https://docs.google.com/spreadsheets/d/1odTftcumb2zOdd0yWUe_rsGO7qKX53zh/edit#gid=703983180) por enquanto até levar para o metabase

**Comment by Cesar-Augusto-cw** [comment]
Pendente: Quebrar visualizações por tags na planilha
