### ISSUE TITLE
Granular WF de Defeitos Gerais

### ISSUE THREAD

**Issue by luhnery** [luhnery/Blackops#17]

**Comment by Cesar-Augusto-cw** [comment]
Atividades realizadas 

Levantamento de assuntos dos chats do período (08/03) 
Criação de nova planilha dinâmica (10/03)
Levantamento das semanas 9 e 10 do General Anomalies POS (16/03)

Planilha de análise:
https://docs.google.com/spreadsheets/d/1JA7kylbib2qT4f9G0afad8ncNu_mg-QzBVn8SC2HXXk/edit#gid=219751420

Dashboards:
https://datastudio.google.com/reporting/9c12db31-9bd9-4ead-a238-7e2b4233d834

**Comment by Cesar-Augusto-cw** [comment]
Finalização do projeto.

Implementado inserção de subtags pelos analistas no chat para controle.

https://metabase-dot-infinitepay-production.rj.r.appspot.com/question/3065-amount-of-chats-pos-subtags?CALENDAR_START=2022-03-14&CALENDAR_END=2022-03-22
